version: '3.8'

services:
  web:
    build: ./web
    container_name: 2022bcd0015-web
    ports:
      - "8080:5000"
    depends_on:
      - db
    networks:
      - app_network

  worker:
    build: ./worker
    container_name: 2022bcd0015-worker
    depends_on:
      - redis
    networks:
      - app_network

  db:
    image: postgres
    container_name: 2022bcd0015-db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis
    container_name: 2022bcd0015-redis
    restart: always
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:

